from numpy_rework.npr_math import mul_List
from numpy_rework.npr_math import sum_List
from numpy_rework.npr_math import subt_List
from numpy_rework.npr_math import div_List
from numpy_rework.dimension import ndim
from numpy_rework.shape import shape
#from numpy_rework.array import array 
from numpy_rework.rc import rc
from numpy_rework.size import size
